# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'HomeControl' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeControl
  pod 'JBChartView'

  target 'HomeControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomeControlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
